/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface BeautyBusiness {
  business_name: string;
  slug: string;
  verified_status: boolean;
  primary_category: string;
  rank_tier: string;
  area: string;
  suburb: string;
  google_rating: number;
  review_count: number;
  featured_image: string;
  source_platform: string;
  secondary_categories: string;
  service_tags: string;
  google_maps_url: string;
  phone: string;
  whatsapp: string;
  website: string;
  booking_url: string;
  instagram: string;
  street_address: string;
  claim_status: string;
  claim_score: number;
  claim_priority: string;
  lead_temperature: string;
  avg_ticket_value: number;
  monthly_booking_estimate: number;
  estimated_monthly_gmv: number;
  annual_gmv_projection: number;
  commission_revenue_potential: number;
  ltv_score: number;
  takeover_target: boolean;
  search_keywords: string;
}

export const beautyData: BeautyBusiness[] = [
  {
    "business_name": "Urban Escape Studio",
    "slug": "urban-escape-studio-0",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Randpark Ridge",
    "suburb": "Randpark Ridge",
    "google_rating": 3.6,
    "review_count": 39,
    "featured_image": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Snupit",
    "secondary_categories": "Beauty Salons, Waxing Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Urban+Escape+Studio,+27 79 413 3392",
    "phone": "+27 79 413 3392",
    "whatsapp": "+27 79 413 3392",
    "website": "https://urbanescapestudio.co.za",
    "booking_url": "https://booksy.com/en-za/s/urban-escape-studio",
    "instagram": "@urban_escape_studio",
    "street_address": "194 Dale Lace Ave, Randpark Ridge",
    "claim_status": "CLAIMED",
    "claim_score": 85,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 450,
    "monthly_booking_estimate": 91,
    "estimated_monthly_gmv": 40950,
    "annual_gmv_projection": 491400,
    "commission_revenue_potential": 6142.5,
    "ltv_score": 79,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Randpark Ridge beauty"
  },
  {
    "business_name": "The Skin Sanctuary",
    "slug": "skin-sanctuary",
    "verified_status": true,
    "primary_category": "Aesthetic Clinics",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.9,
    "review_count": 215,
    "featured_image": "https://images.unsplash.com/photo-1512290923902-8a9f81dc2069?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Facials, Chemical Peels",
    "service_tags": "Skin, Facial, Glow",
    "google_maps_url": "https://maps.google.com/?q=The+Skin+Sanctuary+Fourways",
    "phone": "+27 11 465 9999",
    "whatsapp": "+27 11 465 9999",
    "website": "https://skinsanctuary.co.za",
    "booking_url": "https://booksy.com/en-za/s/skin-sanctuary",
    "instagram": "@skin_sanctuary",
    "street_address": "12 Sunset Ave, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 95,
    "claim_priority": "High",
    "lead_temperature": "Hot",
    "avg_ticket_value": 850,
    "monthly_booking_estimate": 150,
    "estimated_monthly_gmv": 127500,
    "annual_gmv_projection": 1530000,
    "commission_revenue_potential": 19125,
    "ltv_score": 92,
    "takeover_target": true,
    "search_keywords": "Skin, Aesthetic Clinics, Fourways"
  },
  {
    "business_name": "Legends Barber",
    "slug": "legends-barber",
    "verified_status": true,
    "primary_category": "Barbers",
    "rank_tier": "Tier 1",
    "area": "Sandton",
    "suburb": "Sandton",
    "google_rating": 4.7,
    "review_count": 1200,
    "featured_image": "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Men's Grooming, Haircut",
    "service_tags": "Fade, Beard, Style",
    "google_maps_url": "https://maps.google.com/?q=Legends+Barber+Sandton",
    "phone": "+27 11 883 0000",
    "whatsapp": "+27 11 883 0000",
    "website": "https://legends-barber.com",
    "booking_url": "https://legends-barber.com/bookings",
    "instagram": "@legends_barber",
    "street_address": "Sandton City Mall, Sandton",
    "claim_status": "CLAIMED",
    "claim_score": 99,
    "claim_priority": "Elite",
    "lead_temperature": "Hot",
    "avg_ticket_value": 250,
    "monthly_booking_estimate": 800,
    "estimated_monthly_gmv": 200000,
    "annual_gmv_projection": 2400000,
    "commission_revenue_potential": 30000,
    "ltv_score": 99,
    "takeover_target": true,
    "search_keywords": "Barber, Sandton, Fade"
  },
  {
    "business_name": "Sorbet Drybar",
    "slug": "sorbet-drybar",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 2",
    "area": "Sandton",
    "suburb": "Sandton",
    "google_rating": 4.5,
    "review_count": 450,
    "featured_image": "https://images.unsplash.com/photo-1562322140-8baeeec3717d?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Blowout, Styling",
    "service_tags": "Wash, Blow, Style",
    "google_maps_url": "https://maps.google.com/?q=Sorbet+Drybar+Sandton",
    "phone": "+27 11 784 0000",
    "whatsapp": "+27 11 784 0000",
    "website": "https://sorbet.co.za",
    "booking_url": "https://sorbet.co.za/bookings",
    "instagram": "@sorbet_drybar",
    "street_address": "Morningside Shopping Centre, Sandton",
    "claim_status": "CLAIMED",
    "claim_score": 88,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 400,
    "monthly_booking_estimate": 300,
    "estimated_monthly_gmv": 120000,
    "annual_gmv_projection": 1440000,
    "commission_revenue_potential": 18000,
    "ltv_score": 85,
    "takeover_target": false,
    "search_keywords": "Hair, Drybar, Sandton"
  },
  {
    "business_name": "Sorbet Fourways Mall",
    "slug": "sorbet-fourways-mall",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "premium",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.5,
    "review_count": 890,
    "featured_image": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Nail Salons, Skin Care",
    "service_tags": "Nails, Waxing, Sorbet",
    "google_maps_url": "https://maps.app.goo.gl/T4T4T4T4T4T4T4T4",
    "phone": "+27 11 465 5555",
    "whatsapp": "+27 11 465 5555",
    "website": "https://sorbet.co.za",
    "booking_url": "https://sorbet.co.za/book",
    "instagram": "@sorbetgroup",
    "street_address": "Fourways Mall Shop G04",
    "claim_status": "CLAIMED",
    "claim_score": 98,
    "claim_priority": "Elite",
    "lead_temperature": "Hot",
    "avg_ticket_value": 450,
    "monthly_booking_estimate": 1200,
    "estimated_monthly_gmv": 540000,
    "annual_gmv_projection": 6480000,
    "commission_revenue_potential": 81000,
    "ltv_score": 96,
    "takeover_target": true,
    "search_keywords": "Nails, Fourways, Sorbet"
  },
  {
    "business_name": "BOA Beauty Bar",
    "slug": "boa-beauty-bar",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.8,
    "review_count": 86,
    "featured_image": "https://images.unsplash.com/photo-1562322140-8baeeec3717d?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Nail Salons, Lash Studios",
    "service_tags": "Nails, Lashes, Mani-Pedi",
    "google_maps_url": "https://maps.google.com/?q=BOA+Beauty+Bar+Fourways",
    "phone": "+27 11 465 0001",
    "whatsapp": "+27 11 465 0001",
    "website": "https://boabeautybar.co.za",
    "booking_url": "https://boabeautybar.co.za/book",
    "instagram": "@boabeautybar",
    "street_address": "Fourways Crossing, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 90,
    "claim_priority": "High",
    "lead_temperature": "Hot",
    "avg_ticket_value": 550,
    "monthly_booking_estimate": 180,
    "estimated_monthly_gmv": 99000,
    "annual_gmv_projection": 1188000,
    "commission_revenue_potential": 14850,
    "ltv_score": 88,
    "takeover_target": true,
    "search_keywords": "Nails, Fourways, Beauty Bar"
  },
  {
    "business_name": "Angelic Beauty Salon",
    "slug": "angelic-beauty-salon",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 2",
    "area": "Randburg",
    "suburb": "Randburg",
    "google_rating": 4.5,
    "review_count": 142,
    "featured_image": "https://images.unsplash.com/photo-1600948836101-f9ffda59d250?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Waxing Studios, Facials",
    "service_tags": "Skin, Waxing, Facial",
    "google_maps_url": "https://maps.google.com/?q=Angelic+Beauty+Salon+Randburg",
    "phone": "+27 11 791 0000",
    "whatsapp": "+27 11 791 0000",
    "website": "https://angelicbeautysalon.co.za",
    "booking_url": "https://booksy.com/en-za/s/angelic-beauty-salon",
    "instagram": "@angelicbeautysalon",
    "street_address": "88 Republic Rd, Randburg",
    "claim_status": "CLAIMED",
    "claim_score": 75,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 400,
    "monthly_booking_estimate": 100,
    "estimated_monthly_gmv": 40000,
    "annual_gmv_projection": 480000,
    "commission_revenue_potential": 6000,
    "ltv_score": 70,
    "takeover_target": false,
    "search_keywords": "Beauty, Randburg, Waxing"
  },
  {
    "business_name": "Sorbet Randridge Mall",
    "slug": "sorbet-randridge",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 1",
    "area": "Randpark Ridge",
    "suburb": "Randpark Ridge",
    "google_rating": 4.6,
    "review_count": 320,
    "featured_image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Nail Salons, Skin Care",
    "service_tags": "Sorbet, Nails, Skin",
    "google_maps_url": "https://maps.google.com/?q=Sorbet+Randridge+Mall",
    "phone": "+27 11 791 0000",
    "whatsapp": "+27 11 791 0000",
    "website": "https://sorbet.co.za",
    "booking_url": "https://sorbet.co.za/book",
    "instagram": "@sorbetgroup",
    "street_address": "Randridge Mall, Randpark Ridge",
    "claim_status": "CLAIMED",
    "claim_score": 98,
    "claim_priority": "Elite",
    "lead_temperature": "Hot",
    "avg_ticket_value": 650,
    "monthly_booking_estimate": 450,
    "estimated_monthly_gmv": 292500,
    "annual_gmv_projection": 3510000,
    "commission_revenue_potential": 43875,
    "ltv_score": 95,
    "takeover_target": true,
    "search_keywords": "Sorbet, Randpark Ridge, Nails"
  },
  {
    "business_name": "The Salon Pineslopes",
    "slug": "salon-pineslopes",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.9,
    "review_count": 180,
    "featured_image": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Styling, Colour",
    "service_tags": "Paul Mitchell, Hair, Style",
    "google_maps_url": "https://maps.google.com/?q=The+Salon+Pineslopes",
    "phone": "+27 11 465 0000",
    "whatsapp": "+27 11 465 0000",
    "website": "https://thesalonpineslopes.co.za",
    "booking_url": "https://thesalonpineslopes.co.za/book",
    "instagram": "@thesalonpineslopes",
    "street_address": "Pineslopes Shopping Centre, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 94,
    "claim_priority": "Elite",
    "lead_temperature": "Hot",
    "avg_ticket_value": 1100,
    "monthly_booking_estimate": 250,
    "estimated_monthly_gmv": 275000,
    "annual_gmv_projection": 3300000,
    "commission_revenue_potential": 41250,
    "ltv_score": 90,
    "takeover_target": true,
    "search_keywords": "Hair, Fourways, Paul Mitchell"
  },
  {
    "business_name": "Life Day Spa Fourways",
    "slug": "life-day-spa-fourways",
    "verified_status": true,
    "primary_category": "Day Spas",
    "rank_tier": "premium",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.6,
    "review_count": 1240,
    "featured_image": "https://images.unsplash.com/photo-1544161515-4ae6ce6fe858?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Massage, Facials",
    "service_tags": "Wellness, Massage, Spa",
    "google_maps_url": "https://maps.app.goo.gl/9R6P6Z7Zz7Zz7Zz7",
    "phone": "+27 11 465 7777",
    "whatsapp": "+27 11 465 7777",
    "website": "https://lifedayspafourways.co.za",
    "booking_url": "https://lifedayspafourways.co.za/book",
    "instagram": "@lifedayspafourways",
    "street_address": "Design Quarter, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 99,
    "claim_priority": "Elite",
    "lead_temperature": "Hot",
    "avg_ticket_value": 1500,
    "monthly_booking_estimate": 800,
    "estimated_monthly_gmv": 1200000,
    "annual_gmv_projection": 14400000,
    "commission_revenue_potential": 180000,
    "ltv_score": 98,
    "takeover_target": true,
    "search_keywords": "Spa, Fourways, Massage"
  },
  {
    "business_name": "Legends Barber Fourways",
    "slug": "legends-barber-fourways",
    "verified_status": true,
    "primary_category": "Barbers",
    "rank_tier": "premium",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.7,
    "review_count": 520,
    "featured_image": "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Direct",
    "secondary_categories": "Grooming",
    "service_tags": "Fade, Beard, Barber",
    "google_maps_url": "https://maps.app.goo.gl/7X7X7X7X7X7X7X7X",
    "phone": "+27 11 465 1234",
    "whatsapp": "+27 11 465 1234",
    "website": "https://legends-barber.com",
    "booking_url": "https://legends-barber.com/book",
    "instagram": "@legends_barber",
    "street_address": "Fourways Mall",
    "claim_status": "CLAIMED",
    "claim_score": 95,
    "claim_priority": "Elite",
    "lead_temperature": "Hot",
    "avg_ticket_value": 350,
    "monthly_booking_estimate": 1000,
    "estimated_monthly_gmv": 350000,
    "annual_gmv_projection": 4200000,
    "commission_revenue_potential": 52500,
    "ltv_score": 97,
    "takeover_target": true,
    "search_keywords": "Barber, Fourways, Fade"
  },
  {
    "business_name": "Mumbai Xpress Barber Shop",
    "slug": "mumbai-xpress-barber-shop-2",
    "verified_status": true,
    "primary_category": "Barbers",
    "rank_tier": "Tier 2",
    "area": "Randburg CBD",
    "suburb": "Randburg CBD",
    "google_rating": 4.4,
    "review_count": 349,
    "featured_image": "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Day Spas, Medspas",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Mumbai+Xpress+Barber+Shop",
    "phone": "+27 84 414 9369",
    "whatsapp": "+27 84 414 9369",
    "website": "https://mumbaixpressbarbershop.co.za",
    "booking_url": "https://booksy.com/en-za/s/mumbai-xpress-barber-shop",
    "instagram": "@mumbai_xpress_barber_shop",
    "street_address": "2 Fir Dr, Northcliff",
    "claim_status": "CLAIMED",
    "claim_score": 71,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 450,
    "monthly_booking_estimate": 118,
    "estimated_monthly_gmv": 53100,
    "annual_gmv_projection": 637200,
    "commission_revenue_potential": 7965,
    "ltv_score": 68,
    "takeover_target": false,
    "search_keywords": "Barbers, Randburg CBD beauty"
  },
  {
    "business_name": "HAIR at Stacy & co",
    "slug": "hair-at-stacy--co-6",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 1",
    "area": "Linden",
    "suburb": "Linden",
    "google_rating": 5.0,
    "review_count": 310,
    "featured_image": "https://images.unsplash.com/photo-1595476108010-b4d1febb4ff3?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Mobile Beauty Operators, Barbers",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=HAIR+at+Stacy+&+co",
    "phone": "+27 11 023 6432",
    "whatsapp": "+27 11 023 6432",
    "website": "https://hairatstacy&co.co.za",
    "booking_url": "https://booksy.com/en-za/s/hair-at-stacy-&-co",
    "instagram": "@hair_at_stacy_&_co",
    "street_address": "41 Gleneagles Rd, Greenside",
    "claim_status": "CLAIMED",
    "claim_score": 65,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 600,
    "monthly_booking_estimate": 162,
    "estimated_monthly_gmv": 97200,
    "annual_gmv_projection": 1166400,
    "commission_revenue_potential": 14580,
    "ltv_score": 97,
    "takeover_target": true,
    "search_keywords": "Hair Salons, Linden beauty"
  },
  {
    "business_name": "Kara Beauty Studio",
    "slug": "kara-beauty-studio-16",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.9,
    "review_count": 105,
    "featured_image": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Fresha",
    "secondary_categories": "Home-Based Studios, Medspas",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Kara+Beauty+Studio",
    "phone": "+27 11 465 1111",
    "whatsapp": "+27 11 465 1111",
    "website": "https://karabeautystudio.co.za",
    "booking_url": "https://booksy.com/en-za/s/kara-beauty-studio",
    "instagram": "@kara_beauty_studio",
    "street_address": "35 Swallow Drive, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 43,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 1200,
    "monthly_booking_estimate": 119,
    "estimated_monthly_gmv": 142800,
    "annual_gmv_projection": 1713600,
    "commission_revenue_potential": 21420,
    "ltv_score": 51,
    "takeover_target": true,
    "search_keywords": "Beauty Salons, Fourways beauty"
  },
  {
    "business_name": "Cleanse Aesthetics Fourways",
    "slug": "cleanse-aesthetics-fourways-19",
    "verified_status": true,
    "primary_category": "Aesthetic Clinics",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.8,
    "review_count": 173,
    "featured_image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Snupit",
    "secondary_categories": "Beauty Salons, Mobile Beauty Operators",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Cleanse+Aesthetics+Fourways",
    "phone": "+27 11 465 4444",
    "whatsapp": "+27 11 465 4444",
    "website": "https://cleanseaestheticsfourways.co.za",
    "booking_url": "https://booksy.com/en-za/s/cleanse-aesthetics-fourways",
    "instagram": "@cleanse_aesthetics_fourways",
    "street_address": "39b Kingfisher Drive, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 55,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 1200,
    "monthly_booking_estimate": 240,
    "estimated_monthly_gmv": 288000,
    "annual_gmv_projection": 3456000,
    "commission_revenue_potential": 43200,
    "ltv_score": 72,
    "takeover_target": true,
    "search_keywords": "Aesthetic Clinics, Fourways beauty"
  },
  {
    "business_name": "Dolce Vita Beauty Centre",
    "slug": "dolce-vita-beauty-centre-3",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 3",
    "area": "Randpark Ridge",
    "suburb": "Randpark Ridge",
    "google_rating": 3.8,
    "review_count": 89,
    "featured_image": "https://images.unsplash.com/photo-1540555700478-4be289fbecee?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Braiding Studios, Lash Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Dolce+Vita+Beauty+Centre",
    "phone": "+27 11 792 9754",
    "whatsapp": "+27 11 792 9754",
    "website": "https://dolcevitabeautycentre.co.za",
    "booking_url": "https://booksy.com/en-za/s/dolce-vita-beauty-centre",
    "instagram": "@dolce_vita_beauty_centre",
    "street_address": "71 Randpark Dr, Randpark Ridge",
    "claim_status": "CLAIMED",
    "claim_score": 81,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 1200,
    "monthly_booking_estimate": 226,
    "estimated_monthly_gmv": 271200,
    "annual_gmv_projection": 3254400,
    "commission_revenue_potential": 40680,
    "ltv_score": 86,
    "takeover_target": false,
    "search_keywords": "Beauty Salons, Randpark Ridge beauty"
  },
  {
    "business_name": "Sai Yashvi Unisex Hair And Beauty",
    "slug": "sai-yashvi-unisex-hair-and-beauty-5",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 3",
    "area": "Olivedale",
    "suburb": "Olivedale",
    "google_rating": 4.2,
    "review_count": 284,
    "featured_image": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Fresha",
    "secondary_categories": "Makeup Artists, Braiding Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Sai+Yashvi+Unisex+Hair+And+Beauty",
    "phone": "+27 74 870 8190",
    "whatsapp": "+27 74 870 8190",
    "website": "https://saiyashviunisexhairandbeauty.co.za",
    "booking_url": "https://booksy.com/en-za/s/sai-yashvi-unisex-hair-and-beauty",
    "instagram": "@sai_yashvi_unisex_hair_and_beauty",
    "street_address": "Olive & President Fouche Rd, Olivedale",
    "claim_status": "CLAIMED",
    "claim_score": 92,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 350,
    "monthly_booking_estimate": 236,
    "estimated_monthly_gmv": 82600,
    "annual_gmv_projection": 991200,
    "commission_revenue_potential": 12390,
    "ltv_score": 81,
    "takeover_target": false,
    "search_keywords": "Beauty Salons, Olivedale beauty"
  },
  {
    "business_name": "Daniella's Hair Salon",
    "slug": "daniellas-hair-salon-8",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Boskruin",
    "suburb": "Boskruin",
    "google_rating": 3.9,
    "review_count": 345,
    "featured_image": "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Beauty Salons, Hair Salons",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Daniella's+Hair+Salon",
    "phone": "+27 10 447 6623",
    "whatsapp": "+27 10 447 6623",
    "website": "https://daniellashairsalon.co.za",
    "booking_url": "https://booksy.com/en-za/s/daniella's-hair-salon",
    "instagram": "@daniellas_hair_salon",
    "street_address": "Summerfield Shopping Centre, Boskruin",
    "claim_status": "CLAIMED",
    "claim_score": 42,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 350,
    "monthly_booking_estimate": 49,
    "estimated_monthly_gmv": 17150,
    "annual_gmv_projection": 205800,
    "commission_revenue_potential": 2572.5,
    "ltv_score": 84,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Boskruin beauty"
  },
  {
    "business_name": "TrimZ Salon Adean",
    "slug": "trimz-salon-adean-9",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Sharonlea",
    "suburb": "Sharonlea",
    "google_rating": 3.5,
    "review_count": 286,
    "featured_image": "https://images.unsplash.com/photo-1593702275677-f916c8c96042?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Snupit",
    "secondary_categories": "Makeup Artists, Aesthetic Clinics",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=TrimZ+Salon+Adean",
    "phone": "+27 64 429 4794",
    "whatsapp": "+27 64 429 4794",
    "website": "https://trimzsalonadean.co.za",
    "booking_url": "https://booksy.com/en-za/s/trimz-salon-adean",
    "instagram": "@trimz_salon_adean",
    "street_address": "228 Camphers St, Sharonlea",
    "claim_status": "CLAIMED",
    "claim_score": 55,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 600,
    "monthly_booking_estimate": 142,
    "estimated_monthly_gmv": 85200,
    "annual_gmv_projection": 1022400,
    "commission_revenue_potential": 12780,
    "ltv_score": 60,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Sharonlea beauty"
  }
];

// Add logic for simulating the 800 results (just for the demo sake as I can't put 800 rows here manually)
// I will generate the remaining 790 rows programmatically with some variety to show the filter efficiency.

const subCities = ["Randpark Ridge", "Blairgowrie", "Randburg CBD", "Linden", "Fourways", "Olivedale", "Boskruin", "Sharonlea", "Bryanston", "Lonehill", "Ferndale", "North Riding", "Cosmo City", "Robindale", "Witkoppen", "Douglasdale", "Craigavon", "Petervale", "Magaliessig", "Beverley", "Kya Sands", "Weltevreden Park", "Radiokop", "Bordeaux", "Robin Hills"];
const categories = ["Hair Salons", "Barbers", "Beauty Salons", "Nail Salons", "Aesthetic Clinics", "Day Spas", "Medspas", "Braiding Studios", "Lash Studios", "Brow Bars", "Waxing Studios", "Makeup Artists", "Home-Based Studios", "Natural Hair Specialists", "Mobile Beauty Operators", "Nail Tech Studios"];

const namePrefixes = ["Elite", "Royal", "Urban", "The", "Boutique", "Pure", "Glow", "Aura", "Velvet", "Silk", "Lush", "Divine", "Chic", "Nova", "Zen", "Studio", "House of"];
const nameSuffixes = ["Beauty", "Hair", "Studio", "Parlour", "Lounge", "Bar", "Spa", "Clinic", "Concept", "Atelier", "Sanctuary", "Escapes", "Design", "Artistry"];

const catImages: Record<string, string[]> = {
  "Hair Salons": [
    "https://images.unsplash.com/photo-1560066984-138dadb4c035",
    "https://images.unsplash.com/photo-1522337660859-02fbefca4702",
    "https://images.unsplash.com/photo-1595476108010-b4d1febb4ff3"
  ],
  "Barbers": [
    "https://images.unsplash.com/photo-1503951914875-452162b0f3f1",
    "https://images.unsplash.com/photo-1599351431247-f579338389b1",
    "https://images.unsplash.com/photo-1512690199101-8d74c88a5421"
  ],
  "Nail Salons": [
    "https://images.unsplash.com/photo-1604654894610-df63bc536371",
    "https://images.unsplash.com/photo-1627052912443-42e77516d2ca",
    "https://images.unsplash.com/photo-1632345031435-8727f6897d53"
  ],
  "Beauty Salons": [
    "https://images.unsplash.com/photo-1562322140-8baeeec3717d",
    "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9",
    "https://images.unsplash.com/photo-1540555700478-4be289fbecee"
  ]
};

for (let i = 15; i < 800; i++) {
  const rating = (Math.random() * (5.0 - 3.8) + 3.8).toFixed(1);
  const reviews = Math.floor(Math.random() * 800) + 10;
  const suburb = subCities[Math.floor(Math.random() * subCities.length)];
  const category = categories[Math.floor(Math.random() * categories.length)];
  const isVerified = Math.random() > 0.4;
  const tier = parseFloat(rating) >= 4.7 && reviews >= 150 ? "Tier 1" : (parseFloat(rating) >= 4.2 ? "Tier 2" : "Tier 3");
  
  const prefix = namePrefixes[Math.floor(Math.random() * namePrefixes.length)];
  const suffix = nameSuffixes[Math.floor(Math.random() * nameSuffixes.length)];
  const bName = `${prefix} ${suffix} ${i}`;
  
  const catImgs = catImages[category] || catImages["Beauty Salons"];
  const baseImg = catImgs[Math.floor(Math.random() * catImgs.length)];

  beautyData.push({
    "business_name": bName,
    "slug": `${bName.toLowerCase().replace(/\s+/g, '-')}-${i}`,
    "verified_status": isVerified,
    "primary_category": category,
    "rank_tier": tier,
    "area": suburb,
    "suburb": suburb,
    "google_rating": parseFloat(rating),
    "review_count": reviews,
    "featured_image": `${baseImg}?auto=format&fit=crop&q=80&w=800`,
    "source_platform": Math.random() > 0.5 ? "Fresha" : "Booksy",
    "secondary_categories": `${categories[Math.floor(Math.random() * categories.length)]}, ${categories[Math.floor(Math.random() * categories.length)]}`,
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": `https://maps.google.com/?q=${encodeURIComponent(bName)}`,
    "phone": `+27 ${Math.floor(Math.random() * 90 + 10)} ${Math.floor(Math.random() * 900 + 100)} ${Math.floor(Math.random() * 9000 + 1000)}`,
    "whatsapp": `+27 ${Math.floor(Math.random() * 90 + 10)} ${Math.floor(Math.random() * 900 + 100)} ${Math.floor(Math.random() * 9000 + 1000)}`,
    "website": `https://${bName.toLowerCase().replace(/\s+/g, '')}.co.za`,
    "booking_url": `https://booksy.com/en-za/s/${bName.toLowerCase().replace(/\s+/g, '-')}`,
    "instagram": `@${bName.toLowerCase().replace(/\s+/g, '_')}`,
    "street_address": `${Math.floor(Math.random() * 500)} Main Rd, ${suburb}`,
    "claim_status": isVerified ? "CLAIMED" : "UNCLAIMED",
    "claim_score": Math.floor(Math.random() * 70 + 30),
    "claim_priority": Math.random() > 0.8 ? "Hot" : "Warm",
    "lead_temperature": Math.random() > 0.8 ? "Hot" : "Warm",
    "avg_ticket_value": [350, 450, 600, 850, 1200][Math.floor(Math.random() * 5)],
    "monthly_booking_estimate": Math.floor(Math.random() * 210 + 40),
    "estimated_monthly_gmv": 0,
    "annual_gmv_projection": 0,
    "commission_revenue_potential": 0,
    "ltv_score": Math.floor(Math.random() * 50 + 50),
    "takeover_target": tier === "Tier 1" ? Math.random() > 0.5 : false,
    "search_keywords": `${category}, ${suburb} beauty, ${bName}`
  });
}
