/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface BeautyBusiness {
  business_name: string;
  slug: string;
  verified_status: boolean;
  primary_category: string;
  rank_tier: string;
  area: string;
  suburb: string;
  google_rating: number;
  review_count: number;
  featured_image: string;
  source_platform: string;
  secondary_categories: string;
  service_tags: string;
  google_maps_url: string;
  phone: string;
  whatsapp: string;
  website: string;
  booking_url: string;
  instagram: string;
  street_address: string;
  claim_status: string;
  claim_score: number;
  claim_priority: string;
  lead_temperature: string;
  avg_ticket_value: number;
  monthly_booking_estimate: number;
  estimated_monthly_gmv: number;
  annual_gmv_projection: number;
  commission_revenue_potential: number;
  ltv_score: number;
  takeover_target: boolean;
  search_keywords: string;
}

export const beautyData: BeautyBusiness[] = [
  {
    "business_name": "Urban Escape Studio",
    "slug": "urban-escape-studio-0",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Randpark Ridge",
    "suburb": "Randpark Ridge",
    "google_rating": 3.6,
    "review_count": 39,
    "featured_image": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Snupit",
    "secondary_categories": "Beauty Salons, Waxing Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Urban+Escape+Studio,+27 79 413 3392",
    "phone": "+27 79 413 3392",
    "whatsapp": "+27 79 413 3392",
    "website": "https://urbanescapestudio.co.za",
    "booking_url": "https://booksy.com/en-za/s/urban-escape-studio",
    "instagram": "@urban_escape_studio",
    "street_address": "194 Dale Lace Ave, Randpark Ridge",
    "claim_status": "CLAIMED",
    "claim_score": 85,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 450,
    "monthly_booking_estimate": 91,
    "estimated_monthly_gmv": 40950,
    "annual_gmv_projection": 491400,
    "commission_revenue_potential": 6142.5,
    "ltv_score": 79,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Randpark Ridge beauty"
  },
  {
    "business_name": "Awesome Hair",
    "slug": "awesome-hair-1",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Blairgowrie",
    "suburb": "Blairgowrie",
    "google_rating": 3.8,
    "review_count": 378,
    "featured_image": "https://images.unsplash.com/photo-1562322140-8baeeec3717d?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Fresha",
    "secondary_categories": "Day Spas, Nail Tech Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Awesome+Hair",
    "phone": "+27 82 561 3645",
    "whatsapp": "+27 82 561 3645",
    "website": "https://awesomehair.co.za",
    "booking_url": "https://booksy.com/en-za/s/awesome-hair",
    "instagram": "@awesome_hair",
    "street_address": "Valley Centre, 396 Jan Smuts Ave, Craighall Park",
    "claim_status": "CLAIMED",
    "claim_score": 33,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 350,
    "monthly_booking_estimate": 129,
    "estimated_monthly_gmv": 45150,
    "annual_gmv_projection": 541800,
    "commission_revenue_potential": 6772.5,
    "ltv_score": 98,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Blairgowrie beauty"
  },
  {
    "business_name": "Mumbai Xpress Barber Shop",
    "slug": "mumbai-xpress-barber-shop-2",
    "verified_status": true,
    "primary_category": "Barbers",
    "rank_tier": "Tier 2",
    "area": "Randburg CBD",
    "suburb": "Randburg CBD",
    "google_rating": 4.4,
    "review_count": 349,
    "featured_image": "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Day Spas, Medspas",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Mumbai+Xpress+Barber+Shop",
    "phone": "+27 84 414 9369",
    "whatsapp": "+27 84 414 9369",
    "website": "https://mumbaixpressbarbershop.co.za",
    "booking_url": "https://booksy.com/en-za/s/mumbai-xpress-barber-shop",
    "instagram": "@mumbai_xpress_barber_shop",
    "street_address": "2 Fir Dr, Northcliff",
    "claim_status": "CLAIMED",
    "claim_score": 71,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 450,
    "monthly_booking_estimate": 118,
    "estimated_monthly_gmv": 53100,
    "annual_gmv_projection": 637200,
    "commission_revenue_potential": 7965,
    "ltv_score": 68,
    "takeover_target": false,
    "search_keywords": "Barbers, Randburg CBD beauty"
  },
  {
    "business_name": "HAIR at Stacy & co",
    "slug": "hair-at-stacy--co-6",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 1",
    "area": "Linden",
    "suburb": "Linden",
    "google_rating": 5.0,
    "review_count": 310,
    "featured_image": "https://images.unsplash.com/photo-1595476108010-b4d1febb4ff3?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Mobile Beauty Operators, Barbers",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=HAIR+at+Stacy+&+co",
    "phone": "+27 11 023 6432",
    "whatsapp": "+27 11 023 6432",
    "website": "https://hairatstacy&co.co.za",
    "booking_url": "https://booksy.com/en-za/s/hair-at-stacy-&-co",
    "instagram": "@hair_at_stacy_&_co",
    "street_address": "41 Gleneagles Rd, Greenside",
    "claim_status": "CLAIMED",
    "claim_score": 65,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 600,
    "monthly_booking_estimate": 162,
    "estimated_monthly_gmv": 97200,
    "annual_gmv_projection": 1166400,
    "commission_revenue_potential": 14580,
    "ltv_score": 97,
    "takeover_target": true,
    "search_keywords": "Hair Salons, Linden beauty"
  },
  {
    "business_name": "Kara Beauty Studio",
    "slug": "kara-beauty-studio-16",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.9,
    "review_count": 105,
    "featured_image": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Fresha",
    "secondary_categories": "Home-Based Studios, Medspas",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Kara+Beauty+Studio",
    "phone": "+27 11 465 1111",
    "whatsapp": "+27 11 465 1111",
    "website": "https://karabeautystudio.co.za",
    "booking_url": "https://booksy.com/en-za/s/kara-beauty-studio",
    "instagram": "@kara_beauty_studio",
    "street_address": "35 Swallow Drive, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 43,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 1200,
    "monthly_booking_estimate": 119,
    "estimated_monthly_gmv": 142800,
    "annual_gmv_projection": 1713600,
    "commission_revenue_potential": 21420,
    "ltv_score": 51,
    "takeover_target": true,
    "search_keywords": "Beauty Salons, Fourways beauty"
  },
  {
    "business_name": "Cleanse Aesthetics Fourways",
    "slug": "cleanse-aesthetics-fourways-19",
    "verified_status": true,
    "primary_category": "Aesthetic Clinics",
    "rank_tier": "Tier 1",
    "area": "Fourways",
    "suburb": "Fourways",
    "google_rating": 4.8,
    "review_count": 173,
    "featured_image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Snupit",
    "secondary_categories": "Beauty Salons, Mobile Beauty Operators",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Cleanse+Aesthetics+Fourways",
    "phone": "+27 11 465 4444",
    "whatsapp": "+27 11 465 4444",
    "website": "https://cleanseaestheticsfourways.co.za",
    "booking_url": "https://booksy.com/en-za/s/cleanse-aesthetics-fourways",
    "instagram": "@cleanse_aesthetics_fourways",
    "street_address": "39b Kingfisher Drive, Fourways",
    "claim_status": "CLAIMED",
    "claim_score": 55,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 1200,
    "monthly_booking_estimate": 240,
    "estimated_monthly_gmv": 288000,
    "annual_gmv_projection": 3456000,
    "commission_revenue_potential": 43200,
    "ltv_score": 72,
    "takeover_target": true,
    "search_keywords": "Aesthetic Clinics, Fourways beauty"
  },
  {
    "business_name": "Dolce Vita Beauty Centre",
    "slug": "dolce-vita-beauty-centre-3",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 3",
    "area": "Randpark Ridge",
    "suburb": "Randpark Ridge",
    "google_rating": 3.8,
    "review_count": 89,
    "featured_image": "https://images.unsplash.com/photo-1540555700478-4be289fbecee?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Braiding Studios, Lash Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Dolce+Vita+Beauty+Centre",
    "phone": "+27 11 792 9754",
    "whatsapp": "+27 11 792 9754",
    "website": "https://dolcevitabeautycentre.co.za",
    "booking_url": "https://booksy.com/en-za/s/dolce-vita-beauty-centre",
    "instagram": "@dolce_vita_beauty_centre",
    "street_address": "71 Randpark Dr, Randpark Ridge",
    "claim_status": "CLAIMED",
    "claim_score": 81,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 1200,
    "monthly_booking_estimate": 226,
    "estimated_monthly_gmv": 271200,
    "annual_gmv_projection": 3254400,
    "commission_revenue_potential": 40680,
    "ltv_score": 86,
    "takeover_target": false,
    "search_keywords": "Beauty Salons, Randpark Ridge beauty"
  },
  {
    "business_name": "Sai Yashvi Unisex Hair And Beauty",
    "slug": "sai-yashvi-unisex-hair-and-beauty-5",
    "verified_status": true,
    "primary_category": "Beauty Salons",
    "rank_tier": "Tier 3",
    "area": "Olivedale",
    "suburb": "Olivedale",
    "google_rating": 4.2,
    "review_count": 284,
    "featured_image": "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Fresha",
    "secondary_categories": "Makeup Artists, Braiding Studios",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Sai+Yashvi+Unisex+Hair+And+Beauty",
    "phone": "+27 74 870 8190",
    "whatsapp": "+27 74 870 8190",
    "website": "https://saiyashviunisexhairandbeauty.co.za",
    "booking_url": "https://booksy.com/en-za/s/sai-yashvi-unisex-hair-and-beauty",
    "instagram": "@sai_yashvi_unisex_hair_and_beauty",
    "street_address": "Olive & President Fouche Rd, Olivedale",
    "claim_status": "CLAIMED",
    "claim_score": 92,
    "claim_priority": "High",
    "lead_temperature": "Warm",
    "avg_ticket_value": 350,
    "monthly_booking_estimate": 236,
    "estimated_monthly_gmv": 82600,
    "annual_gmv_projection": 991200,
    "commission_revenue_potential": 12390,
    "ltv_score": 81,
    "takeover_target": false,
    "search_keywords": "Beauty Salons, Olivedale beauty"
  },
  {
    "business_name": "Daniella's Hair Salon",
    "slug": "daniellas-hair-salon-8",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Boskruin",
    "suburb": "Boskruin",
    "google_rating": 3.9,
    "review_count": 345,
    "featured_image": "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Booksy",
    "secondary_categories": "Beauty Salons, Hair Salons",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=Daniella's+Hair+Salon",
    "phone": "+27 10 447 6623",
    "whatsapp": "+27 10 447 6623",
    "website": "https://daniellashairsalon.co.za",
    "booking_url": "https://booksy.com/en-za/s/daniella's-hair-salon",
    "instagram": "@daniellas_hair_salon",
    "street_address": "Summerfield Shopping Centre, Boskruin",
    "claim_status": "CLAIMED",
    "claim_score": 42,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 350,
    "monthly_booking_estimate": 49,
    "estimated_monthly_gmv": 17150,
    "annual_gmv_projection": 205800,
    "commission_revenue_potential": 2572.5,
    "ltv_score": 84,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Boskruin beauty"
  },
  {
    "business_name": "TrimZ Salon Adean",
    "slug": "trimz-salon-adean-9",
    "verified_status": true,
    "primary_category": "Hair Salons",
    "rank_tier": "Tier 3",
    "area": "Sharonlea",
    "suburb": "Sharonlea",
    "google_rating": 3.5,
    "review_count": 286,
    "featured_image": "https://images.unsplash.com/photo-1593702275677-f916c8c96042?auto=format&fit=crop&q=80&w=800",
    "source_platform": "Snupit",
    "secondary_categories": "Makeup Artists, Aesthetic Clinics",
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": "https://maps.google.com/?q=TrimZ+Salon+Adean",
    "phone": "+27 64 429 4794",
    "whatsapp": "+27 64 429 4794",
    "website": "https://trimzsalonadean.co.za",
    "booking_url": "https://booksy.com/en-za/s/trimz-salon-adean",
    "instagram": "@trimz_salon_adean",
    "street_address": "228 Camphers St, Sharonlea",
    "claim_status": "CLAIMED",
    "claim_score": 55,
    "claim_priority": "Medium",
    "lead_temperature": "Warm",
    "avg_ticket_value": 600,
    "monthly_booking_estimate": 142,
    "estimated_monthly_gmv": 85200,
    "annual_gmv_projection": 1022400,
    "commission_revenue_potential": 12780,
    "ltv_score": 60,
    "takeover_target": false,
    "search_keywords": "Hair Salons, Sharonlea beauty"
  }
];

// Add logic for simulating the 800 results (just for the demo sake as I can't put 800 rows here manually)
// I will generate the remaining 790 rows programmatically with some variety to show the filter efficiency.

const subCities = ["Randpark Ridge", "Blairgowrie", "Randburg CBD", "Linden", "Fourways", "Olivedale", "Boskruin", "Sharonlea", "Bryanston", "Lonehill", "Ferndale", "North Riding", "Cosmo City", "Robindale", "Witkoppen", "Douglasdale", "Craigavon", "Petervale", "Magaliessig", "Beverley", "Kya Sands", "Weltevreden Park", "Radiokop", "Bordeaux", "Robin Hills"];
const categories = ["Hair Salons", "Barbers", "Beauty Salons", "Nail Salons", "Aesthetic Clinics", "Day Spas", "Medspas", "Braiding Studios", "Lash Studios", "Brow Bars", "Waxing Studios", "Makeup Artists", "Home-Based Studios", "Natural Hair Specialists", "Mobile Beauty Operators", "Nail Tech Studios"];

for (let i = 10; i < 800; i++) {
  const rating = (Math.random() * (5.0 - 3.5) + 3.5).toFixed(1);
  const reviews = Math.floor(Math.random() * 500);
  const suburb = subCities[Math.floor(Math.random() * subCities.length)];
  const category = categories[Math.floor(Math.random() * categories.length)];
  const isVerified = Math.random() > 0.3;
  const tier = parseFloat(rating) >= 4.7 && reviews >= 100 ? "Tier 1" : (parseFloat(rating) >= 4.3 ? "Tier 2" : "Tier 3");

  beautyData.push({
    "business_name": `Beauty Venue ${i + 1}`,
    "slug": `beauty-venue-${i + 1}-${i}`,
    "verified_status": isVerified,
    "primary_category": category,
    "rank_tier": tier,
    "area": suburb,
    "suburb": suburb,
    "google_rating": parseFloat(rating),
    "review_count": reviews,
    "featured_image": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800",
    "source_platform": Math.random() > 0.5 ? "Fresha" : "Booksy",
    "secondary_categories": `${categories[Math.floor(Math.random() * categories.length)]}, ${categories[Math.floor(Math.random() * categories.length)]}`,
    "service_tags": "Styling, Cut, Treatment",
    "google_maps_url": `https://maps.google.com/?q=Beauty+Venue+${i + 1}`,
    "phone": `+27 ${Math.floor(Math.random() * 90 + 10)} ${Math.floor(Math.random() * 900 + 100)} ${Math.floor(Math.random() * 9000 + 1000)}`,
    "whatsapp": `+27 ${Math.floor(Math.random() * 90 + 10)} ${Math.floor(Math.random() * 900 + 100)} ${Math.floor(Math.random() * 9000 + 1000)}`,
    "website": `https://beautyvenue${i + 1}.co.za`,
    "booking_url": `https://booksy.com/en-za/s/beauty-venue-${i + 1}`,
    "instagram": `@beauty_venue_${i + 1}`,
    "street_address": `${Math.floor(Math.random() * 500)} Main Rd, ${suburb}`,
    "claim_status": isVerified ? "CLAIMED" : "UNCLAIMED",
    "claim_score": Math.floor(Math.random() * 70 + 30),
    "claim_priority": Math.random() > 0.8 ? "Hot" : "Warm",
    "lead_temperature": Math.random() > 0.8 ? "Hot" : "Warm",
    "avg_ticket_value": [350, 450, 600, 850, 1200][Math.floor(Math.random() * 5)],
    "monthly_booking_estimate": Math.floor(Math.random() * 210 + 40),
    "estimated_monthly_gmv": 0,
    "annual_gmv_projection": 0,
    "commission_revenue_potential": 0,
    "ltv_score": Math.floor(Math.random() * 50 + 50),
    "takeover_target": tier === "Tier 1" ? Math.random() > 0.5 : false,
    "search_keywords": `${category}, ${suburb} beauty`
  });
}
